name: zizmor

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  zizmor:
    name: zizmor
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803
        with:
          persist-credentials: false

      - uses: zizmorcore/zizmor-action@cc914d7f3750a2d13d75c7f184a1060aa0e9d482
        with:
          config: .github/zizmor.yml
          advanced-security: "false"
          annotations: "true"
